from fpdf import FPDF
from datetime import datetime
import textwrap
import re
import math

class PDF(FPDF):
    def __init__(self):
        super().__init__(orientation='L', unit='mm', format='A4')
        self.set_auto_page_break(auto=True, margin=12)

        # --- UNICODE FONTS ---
        self.add_font("DejaVu", "", "fonts/DejaVuSans.ttf", uni=True)
        self.add_font("DejaVu", "B", "fonts/DejaVuSans-Bold.ttf", uni=True)

    def header(self):
        if self.page_no() > 1:
            self.set_font("DejaVu", "I", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 5, "Calmera - Household Resilience Blueprint", 0, 0, "L")
            self.cell(0, 5, f"Page {self.page_no()}", 0, 0, "R")
            self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("DejaVu", "I", 7)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "General guidance only. Always follow official emergency advice.", 0, 0, "C")
        self.set_y(-8)
        self.cell(0, 4, f"Generated by Calmera on {datetime.now().strftime('%d %B %Y')}. All rights reserved.", 0, 0, "C")

    def _clean_text(self, text):
        emoji_pattern = re.compile("["
            u"\U0001F600-\U0001F64F"
            u"\U0001F300-\U0001F5FF"
            u"\U0001F680-\U0001F6FF"
            u"\U0001F1E0-\U0001F1FF"
            u"\U00002702-\U000027B0"
            u"\U000024C2-\U0001F251"
            "]+", flags=re.UNICODE)
        text = emoji_pattern.sub(r'', text)

        replacements = {
            "—": "-", "–": "-", "•": "-", "’": "'", "‘": "'",
            "“": '"', "”": '"', "…": "...", "✓": "[X]", "✗": "[ ]",
            "≥": ">=", "≤": "<=", "→": "->", "←": "<-",
            "°": " deg", "×": "x", "±": "+/-", "█": "#", "░": ".",
            "‑": "-",   # non‑breaking hyphen
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        return text

    def section_title(self, title):
        self.set_font("DejaVu", "B", 14)
        self.set_text_color(0, 51, 102)
        self.cell(0, 8, self._clean_text(title), 0, 1, "L")
        self.ln(2)

    def subsection_title(self, title):
        self.set_font("DejaVu", "B", 11)
        self.set_text_color(0, 51, 102)
        self.cell(0, 7, self._clean_text(title), 0, 1, "L")
        self.ln(1)

    def body_text(self, text):
        self.set_font("DejaVu", "", 9)
        self.set_text_color(0, 0, 0)
        text = self._clean_text(text)
        for line in textwrap.wrap(text, 120):
            self.cell(0, 4, line, 0, 1)
        self.ln(1)

    def bullet_point(self, text):
        self.set_font("DejaVu", "", 9)
        text = self._clean_text(text)
        self.cell(5, 4, "-", 0, 0)
        for line in textwrap.wrap(text, 115):
            self.cell(0, 4, line, 0, 1)
            if line != textwrap.wrap(text, 115)[-1]:
                self.cell(5, 4, " ", 0, 0)
        self.ln(1)

    def draw_progress_bar(self, x, y, width, percentage, label=""):
        self.set_fill_color(230, 230, 230)
        self.rect(x, y, width, 5, 'F')
        fill_width = width * min(1.0, percentage / 100)
        self.set_fill_color(0, 150, 100)
        self.rect(x, y, fill_width, 5, 'F')
        if label:
            self.set_font("DejaVu", "I", 7)
            self.set_text_color(80, 80, 80)
            self.set_xy(x, y-3)
            self.cell(0, 3, self._clean_text(label), 0, 1)

def generate_calmera_pdf(data):
    pdf = PDF()
    pdf.add_page()

    # ----- PAGE 1 -----
    pdf.set_font("DejaVu", "B", 20)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 12, "Household Resilience Blueprint", 0, 1, "C")

    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(
        0, 5,
        f"Tailored for {data['people']} Adult(s), {data['cats']+data['dogs']} Pets | {data['days']}-Day Horizon | Generated {datetime.now().strftime('%d %B %Y')}",
        0, 1, "C"
    )
    pdf.ln(6)

    # Scores
    water_score = min(100, (data['water_total'] / (data['people'] * data['days'] * 3)) * 100)
    power_score = 100 if data['power_battery_wh'] >= 500 else 50
    sanitation_score = 100 if data['has_toilet_plan'] and data['has_cover_material'] else 30
    comms_score = (sum([data['has_radio'], data['has_contacts'], data['has_map']]) / 3) * 100

    overall_score_val = data.get('overall_score', (water_score + power_score + sanitation_score + comms_score) / 4)
    grade = data['grade']
    grade_text = f"Grade: {grade} - {'Well Prepared' if grade in ['A','B'] else 'Action Needed' if grade == 'C' else 'Significant Gaps'}"

    pdf.set_font("DejaVu", "B", 14)
    pdf.cell(0, 8, f"Your Calmera Score: {overall_score_val:.0f}% ({grade_text})", 0, 1)
    pdf.draw_progress_bar(10, pdf.get_y(), 200, overall_score_val)
    pdf.ln(12)

    # Narrative
    pdf.section_title("The Bottom Line")
    pdf.body_text("Your household can handle short disruptions, but you're vulnerable beyond 48 hours. The good news: a single weekend of targeted action closes the gaps.")
    pdf.body_text(f"Your water storage is {'solid' if water_score >= 80 else 'below target'}, and your sanitation plan {'works' if sanitation_score >= 80 else 'needs setup'}. What's missing is backup power capacity and a printed communications kit—both fixable for under $150.")

    # Readiness
    pdf.section_title("Readiness at a Glance")
    pdf.body_text(f"Water Readiness: {water_score:.0f}% — {'Fully covered' if water_score >= 80 else 'Partial coverage'}")
    pdf.body_text(f"Power Backup: {power_score:.0f}% — {'Full backup' if power_score >= 80 else 'Partial coverage'}")
    pdf.body_text(f"Sanitation Plan: {sanitation_score:.0f}% — {'System in place' if sanitation_score >= 80 else 'Missing'}")
    pdf.body_text(f"Communications: {comms_score:.0f}% — {'Complete' if comms_score >= 80 else 'Gaps to address'}")
    pdf.ln(4)

    # Top actions
    pdf.section_title("Your Top 3 Actions This Week")
    for step in data['next_steps'][:3]:
        pdf.bullet_point(step)

    # ----- PAGE 2 -----
    pdf.add_page()
    pdf.section_title("Your Weekend Procurement Plan")

    containers_needed = data['water_containers']

    pdf.subsection_title("Hardware (Bunnings / Mitre 10)")
    pdf.bullet_point(f"{containers_needed} x 20L food-grade water containers")
    pdf.bullet_point("2 x heavy-duty buckets with lids")
    pdf.bullet_point("Sawdust or kitty litter")
    pdf.bullet_point("Heavy-duty rubbish bags")
    pdf.bullet_point("Masking tape + permanent marker")

    pdf.subsection_title("Electronics (PB Tech / Noel Leeming)")
    pdf.bullet_point("2 x 20,000mAh power banks ($~150 Budget Lifeline option for phones/lights)")
    pdf.bullet_point("Battery-powered AM/FM radio + spare batteries")
    pdf.bullet_point("Extra phone charging cables")

    pdf.subsection_title("Supermarket / Pharmacy")
    pdf.bullet_point("Hand sanitiser (2 large pump bottles)")
    pdf.bullet_point("Basic first aid: Panadol, plasters, antiseptic")
    pdf.bullet_point("7 days of non-perishable food you'll actually eat")

    # Calculation transparency
    pdf.ln(4)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("DejaVu", "B", 11)
    pdf.cell(0, 7, "How We Calculated Your Numbers", 0, 1)
    pdf.set_font("DejaVu", "", 9)

    pdf.multi_cell(0, 4, pdf._clean_text(
        "These formulas are based on public health and civil defence guidelines (WHO, Red Cross, NZ Civil Defence) to give you a tailored, realistic plan.\n\n"
        "Water: 3L per person daily (2L drinking + 1L food prep). Pets: 1L/day per dog, 0.2L/day per cat. Climate: +20% for High/Extreme Heat.\n"
        f"Power: Your {data['power_daily_wh']:.0f} Wh daily target aggregates your selected devices (e.g., {data['power_breakdown']['phone_wh']:.0f}Wh phones, {data['power_breakdown']['laptop_wh']:.0f}Wh laptop) plus a 20% buffer.\n"
        "Sanitation: Two-bucket system - 0.1kg cover material per person per day, 0.02L hand sanitiser per person per day.\n"
        "Score: Average of water, power, sanitation, and communications scores, each capped at 100%."
    ), border=0, fill=True)

    pdf.ln(2)

    # Export
    output_data = pdf.output(dest="S")

    if isinstance(output_data, str):
        return output_data.encode("latin-1")
    elif isinstance(output_data, (bytearray, bytes)):
        return bytes(output_data)
    elif output_data is None:
        return bytes(pdf.output())
    else:
        return bytes(output_data)
